### ISSUE TITLE
@coroutine decorator is deprecated in Python 3.8

### ISSUE THREAD

**Issue by xqt** [rtfol/aiohttp-sse-client#12]
WARNING: C:\Python38\lib\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore

**Comment by awarecan** [comment]
That is aiohttp issue. Please update your `aiohttp`
