### ISSUE TITLE
Use credentials from session obj

### ISSUE THREAD

**Issue by spacemanspiff2007** [rtfol/aiohttp-sse-client#27]
I am creating a session object and it holds the auth information.
```python
    HTTP_SESSION = aiohttp.ClientSession(
        json_serialize=dump_json,
        auth=auth
    )
```

I was wondering why I have to pass 'with_credentials' as an option if I already pass the session obj.
```python
        async with sse_client.EventSource(
                url=url ,
                option={'with_credentials': True},
                session=HTTP_SESSION
        )
```

Wouldn't it be possible to check if the session obj holds the auth information and then use this?
Or does this parameter do something else I am not seeing.

**Comment by awarecan** [comment]
Hmmm, I don't even know why we have `with_credentials` option at the first place. It seems not been used anyway.

**Comment by spacemanspiff2007** [comment]
I guess then it's not necessary that I even use this option?
